/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "data_type.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(sensor_data_t, sensor_data_t, AUTO)



